server:
  port: 8888

logging:
  path: logs
  file: userManager.log

spring:
  application:
    name: userManager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 302519898p


mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*